[General]
# Background image (e.g. backgrounds/background1.png or backgrounds/background2.png)
Background="backgrounds/background1.png"

# Visual options
BlurRadius="40"
BatteryPercent="69"
BatteryStatus="Discharging"

# Typography
FontFamily="Outfit"
TimeFont="Outfit"

# Formats
DateFormat="dddd, MMMM d"
TimeFormat="HH:mm"

# Session & User
ShowSessionBadge="false"
